BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Visitings` (
	`visitingid`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`groupid`	INTEGER NOT NULL,
	`studentid`	INTEGER NOT NULL DEFAULT 1,
	`presence`	INTEGER NOT NULL DEFAULT 0,
	`mark`	INTEGER,
	`date`	TEXT NOT NULL,
	FOREIGN KEY(`groupid`) REFERENCES `Groups`(`groupid`) ON DELETE cascade,
	FOREIGN KEY(`studentid`) REFERENCES `Students`(`studentid`) ON DELETE cascade
);
CREATE TABLE IF NOT EXISTS `Students` (
	`studentid`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`groupid`	INTEGER,
	`name`	TEXT NOT NULL,
	`birthdate`	TEXT NOT NULL,
	`ismale`	INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS `Groups` (
	`groupid`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`daysOfWeek`	TEXT,
	`startDate`	TEXT NOT NULL,
	`finishDate`	TEXT NOT NULL
);
COMMIT;
